### ISSUE TITLE
exiv2/xmp_exiv2.hpp missing

### ISSUE THREAD

**Issue by chrylis** [Fimagena/raw2dng#10]
Compilation is failing for me on Gentoo with exiv2 0.26 because the header file `exiv2/xmp_exiv2.hpp` is missing. I believe this has been replaced with `exiv2/xmp.hpp`, and changing the import makes the compilation succeed normally.

**Comment by Fimagena** [comment]
Yes, last version was written against a trunk-snapshot of exiv2 (to enable certain camera-compatibility) which hadn't stabilised its API yet. To be fixed
