### ISSUE TITLE
Is it supposed to be compatible with A7R II?

### ISSUE THREAD

**Issue by oxyc** [Fimagena/raw2dng#5]
Greetings, I just tried out your app with my new A7R II but I can't get the wifi transfer to work. Have you tested it or do you know of anyone who has got it to work?

When I select "Send to Computer" on the Camera, it just states: "Information of the computer where the data is to be saved is not set to the device. Connect the computer to the device with an USB cable and set it."

I've connected the camera to my Nexus 5x through a USB cable and managed to copy the files like that but I cant find a way for the camera to "recognize" the phone as a computer. Therefore I am also unable to transfer RAW files over Wi-Fi.

Any support would be much appreciated.

**Comment by Fimagena** [comment]
Sony requires the camera to know the 'computer' it sends files to. This can
only be done through Sony's proprietary software that comes with the
camera.

You need to first connect the camera to your computer via USB and follow
the instructions in Sony's software before connecting it to your phone via
raw2dng. This only needs to be done once. The phone then pretends to be the
computer.

The next version of raw2dng will be able to work around this requirement by
tricking the camera into thinking it knows the phone already. But I can't
give you an estimate yet when it will be released.

Hope that helps.

**Comment by oxyc** [comment]
> You need to first connect the camera to your computer via USB and follow
> the instructions in Sony's software before connecting it to your phone via
> raw2dng. This only needs to be done once. The phone then pretends to be the
> computer.

Thanks, I appreciate your help. Wasn't sure it was even supposed to work so I gave up pretty quickly. If anyone else arrives here, on OSX it turns out I had to install a different [Wireless Auto Import](http://support.d-imaging.sony.co.jp/imsoft/Mac/wai/us.html) app. I figured PlayMemories Home was enough, but it wasn't.
