### ISSUE TITLE
could you please write a man doc or provide a -h parameter or a wiki to help us understand all the parameters 

### ISSUE THREAD

**Issue by 243750496** [Fimagena/raw2dng#6]
-dcp <filename>      use adobe camera profile
  -e                   embed original
  -j                   convert to JPEG instead of DNG
  -t                   convert to TIFF instead of DNG
  -o <filename>        specify output filename

what is adobe camera profile what's the difference with dng file and what is embed original ????
thx! :)

**Comment by Fimagena** [comment]
I'm accepting patches...

 -dcp: Every DNG file has a colour profile. Embed one manually (Adobe provides a whole collection for many cameras with its DNG converter ) or raw2dng will create a simple one.
 -e: DNG provides an option to embed the complete original raw file into the DNG file

**Comment by 243750496** [comment]
-dcp : what's the simple one the raw2dng created and what's the difference between it and adobe one ? does both is the same?
-e : does it means there's no color profile in the dng file , i am not quite got what the complete original raw file has.

**Comment by Fimagena** [comment]
-dcp: See the code [here]. The default profile is build from the XYZ-matrix that LibRaw / dcRaw provides for each camera. If you'd rather specify yourself, provide your own profile.

-e: It just adds the complete raw-file as backup into the DNG. Nothing to with colour profiles.

 (https://github.com/Fimagena/raw2dng/blob/master/raw2dng/negativeProcessor.cpp#L257)

**Comment by 243750496** [comment]
-dcp so do you mean auto adjustment that libRaw / dcRaw will done automaticly for each image and contain the color profile in it , but what can i specify myself ? the adjustment or the color profile or both?

**Comment by gerein** [comment]
No adjustment. Each camera has just one colour profile. DNG-files include the relevant profile with the raw-data. Adobe has tools to create colour-profiles as .dcp-files. With -dcp you can specify a .dcp-file to be included in the DNG. Without one, raw2dng will create a DNG-compatible profile on-the fly based on camera-specific data supplied by libraw.

**Comment by Fimagena** [comment]
No adjustment. Each camera has just one colour profile. DNG-files include the relevant profile with the raw-data. Adobe has tools to create colour-profiles as .dcp-files. With -dcp you can specify a .dcp-file to be included in the DNG. Without one, raw2dng will create a DNG-compatible profile on-the fly based on camera-specific data supplied by libraw.

**Comment by 243750496** [comment]
-dcp: so dng files contains two part : one is the adjustment of dcp and one is raw data.

 dcp contained the relevant parameters to use to create jpeg. If not specificed it will generate from the default one witch provided by adobe?

am i got the concept all right?
