### ISSUE TITLE
fatal error while building "dng_host.h"

### ISSUE THREAD

**Issue by mantissa-** [Fimagena/raw2dng#9]
Hey,
I'm having some trouble building the application.
This is what I'm getting after I run make:

`Scanning dependencies of target raw2dng
[  8%] Building CXX object CMakeFiles/raw2dng.dir/raw2dng.o
In file included from /home/mantissa/Applications/raw2dng/raw2dng/rawConverter.h:21:0,
                 from /home/mantissa/Applications/raw2dng/raw2dng/raw2dng.cpp:22:
/home/mantissa/Applications/raw2dng/raw2dng/negativeProcessor/processor.h:21:10: fatal error: dng_host.h: No such file or directory
 #include <dng_host.h>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/raw2dng.dir/build.make:62: recipe for target 'CMakeFiles/raw2dng.dir/raw2dng.o' failed
make[2]: *** [CMakeFiles/raw2dng.dir/raw2dng.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/raw2dng.dir/all' failed
make[1]: *** [CMakeFiles/raw2dng.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Fincer** [comment]
Not sure if any help but these are dependencies I've defined for raw2dng in my Arch Linux PKGBUILD:

```
depends=('exiv2' 'libraw' 'expat' 'libjpeg-turbo' 'zlib')
makedepends=('gcc' 'cmake')
```

Additionally, I need to use a custom patch with the following contents for raw2dng:

```
--- a/raw2dng/CMakeLists.txt
+++ b/raw2dng/CMakeLists.txt
@@ -10,7 +10,7 @@
 # configure a header file to pass some of the CMake settings
 # to the source code
 CONFIGURE_FILE ( "${CMAKE_CURRENT_SOURCE_DIR}/config.h.cmake"
-                 "${CMAKE_CURRENT_BINARY_DIR}/config.h" )
+                 "${CMAKE_CURRENT_SOURCE_DIR}/config.h" )
 
 SET( EXIV2_MIN_VERSION "0.21" )
 FIND_PACKAGE( Exiv2 )

--- a/raw2dng/rawConverter.h
+++ b/raw2dng/rawConverter.h
@@ -21,6 +21,7 @@
 #include "negativeProcessor.h"
 
 #include <string>
+#include <functional>
 
 #include "dng_auto_ptr.h"
 #include "dng_preview.h"

```

One thing that takes my attention is the following line in your quote:

```
/home/mantissa/Applications/raw2dng/raw2dng/negativeProcessor/processor.h
```
There seem not to be such file in my compilation environment, neither there is in this repository.

**Comment by Fimagena** [comment]
The "processor.h" suggests that you've downloaded a fork and not the original repository - if that's intentional then you should file your issue with that fork's author.
However,  it looks like your executing cmake in the raw2dng sub-directory, which will not work. You need to execute it in the main directory of the repository to get all dependencies setup.

**Comment by mantissa-** [comment]
Yeah, I was using a fork, but getting the same error about dng_host.h. Posted the wrong output, but the problem persists, my bad.

**Comment by Fimagena** [comment]
Have you tried executing cmake in the main directory of the repo?

**Comment by Fincer** [comment]
Link to the fork? I may give it a try

**Comment by mantissa-** [comment]
Here's my cmake output:
`cmake raw2dng/
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:16 (FIND_PACKAGE):
  By not providing "FindExiv2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Exiv2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Exiv2" with any of
  the following names:

    Exiv2Config.cmake
    exiv2-config.cmake

  Add the installation prefix of "Exiv2" to CMAKE_PREFIX_PATH or set
  "Exiv2_DIR" to a directory containing one of the above files.  If "Exiv2"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Warning at CMakeLists.txt:21 (FIND_PACKAGE):
  By not providing "FindLibRaw.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibRaw", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibRaw" with any
  of the following names:

    LibRawConfig.cmake
    libraw-config.cmake

  Add the installation prefix of "LibRaw" to CMAKE_PREFIX_PATH or set
  "LibRaw_DIR" to a directory containing one of the above files.  If "LibRaw"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/raw2dng-master
`

**Comment by Fimagena** [comment]
You're already in the repo-dir. Try ````cmake .```` instead of ````cmake raw2dng/````.

**Comment by mantissa-** [comment]
Ah, that seems to do better. I'm still missing libraw and exiv2, but I'll have a look at how I can get them installed on my system. I thought they're installed but the version might be off.

Thanks for the help, I'm still quite new to building software. :)

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EXIV2_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
EXIV2_LIBRARY (ADVANCED)
    linked by target "raw2dng" in directory /tmp/raw2dng-master/raw2dng
LIBRAW_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
   used as include directory in directory /tmp/raw2dng-master/raw2dng
LIBRAW_LIBRARY (ADVANCED)
    linked by target "raw2dng" in directory /tmp/raw2dng-master/raw2dng
`

**Comment by Fincer** [comment]
This is what I use in my PKGBUILD (you need to `cd` to the raw2dng main source dir before issuing these commands):

```
mkdir build
cd ./build
cmake ../
make
```

I assume you have `libraw` and `exiv2` installed.

**Comment by Fimagena** [comment]
You need the dev-versions of the libraries to compile against. If you're on Debian or similar you can use ````sudo apt-get install libraw-dev libexiv2-dev libz-dev libexpat-dev libjpeg-dev```` to get the dependencies installed.
To anticipate your next problem after that: you might run into a ````exiv2/xmp_exiv2.hpp: No such file or directory```` error. That's because raw2dng is written against exiv2-trunk. If you hit that issue, either download trunk from GitHub or change the relevant include line to ````exiv2/xmp.hpp````.

**Comment by mantissa-** [comment]
That was exactly what happened, now an error pops up with rawConverter.cpp.o.
https://pastebin.com/TW7d24yR

So close, yet so far. :)

**Comment by Fimagena** [comment]
I cannot see that on my test distributions but I guess Fincer's patch further up (adding ````#include <functional>```` in rawConverter.h) should help. What distro are you on?

**Comment by Fincer** [comment]
`raw2dng/rawConverter.h`

add line

`#include <functional>`

and try again.

**Comment by mantissa-** [comment]
That solved it! Thanks for helping me through the process. :)
For reference, I'm on Xubuntu 18.04.
`make install` ran fine, and I just converted and ARW to dng.

Is there a way to do an entire directory at once, or is it more meant for single files?
I'm using it to process raw files from an a7RII for photoscanning, so I'll have batches of up to 250 photos at times.

EDIT: Nvm, wrote a simple bash script, ignore this. :)

**Comment by Fincer** [comment]
Glad to hear!

You may try a simple for loop (like this bash script, referred as `conv.sh` here) to batch process a directory:

```
!#/bin/bash

# Usage: 
# bash ./conv.sh /path/to/my/pics IMG_FORMAT

# For example:
# bash ./conv.sh /home/user/Pictures NEF

PHOTODIR="${1}"
PHOTOFORMAT="${2}"

PHOTOCOUNT=$(ls -w 1 "${PHOTODIR}" | grep -i "${PHOTOFORMAT}$" | wc -l)
i=1
for file in "${PHOTODIR}"/*.${PHOTOFORMAT}; do
    echo "File: $i/${PHOTOCOUNT}"
    raw2dng ${file}
    let i++
done

```

- Just make sure that compiled `raw2dng` executable is found on your `$PATH` (usually either `/usr/bin/` folder or `/usr/local/bin/` folder).

- Use the script as instructed in the `Usage` section above.

- `IMG_FORMAT` is case sensitive, so `nef` and `NEF` or `cr2` and `CR2` are not the same thing.
